version: '3.4'

services:
  web.bff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IS_ORCHESTRATED=true
      - IdentityUrl=http://identityApi
      - IdentityUrlExternal=http://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:5000
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  watchDog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - HealthChecksUI__HealthChecks__0__Name=Catalog API HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://basketApi/hc
      - HealthChecksUI__HealthChecks__1__Name=Basket API HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://catalogApi/hc
      - HealthChecksUI__HealthChecks__2__Name=Ordering API HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://orderingApi/hc
      - HealthChecksUI__HealthChecks__3__Name=Identity API HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://identityApi/hc
      - HealthChecksUI__HealthChecks__4__Name=Web BFF HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://webBFF/hc
      - IS_ORCHESTRATED=true
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IS_ORCHESTRATED=true
      - IdentityUrl=http://identityApi
      - IdentityUrlExternal=http://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:5000
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IS_ORCHESTRATED=true
      - IdentityUrl=http://identityApi
      - IdentityUrlExternal=http://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:5000
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IS_ORCHESTRATED=true
      - IdentityUrl=http://identityApi
      - IdentityUrlExternal=http://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:5000
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IS_ORCHESTRATED=true
      - Urls__WebBffShoppingClient=https://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:6001
      - Urls__CatalogApi=http://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:7000
      - Urls__BasketApi=http://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:8000
      - Urls__OrderingApi=http://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:9000
      - Urls__WebMVCIdentity=https://${LONTRAY_EXTERNAL_DNS_NAME_OR_IP}:6001 ## test here
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro